### ISSUE TITLE
Update to latest version?

### ISSUE THREAD

**Issue by BattleBrisket** [railsjedi/ruby-stylus-source#6]
Any chance this library is going to update to the latest version of Stylus? Current stable version is **0.49.3**, but this gem is only running **0.42.2**

I am aware that I can run rake update from within the gem directory to get the latest version, but that requires me to install `nodejs` and `npm` (which I don't otherwise need), and obviously I have to make changes to a gem file after installation.

**Comment by railsjedi** [comment]
hey @BattleBrisket I haven't been using this library, but if you'd like to update it I can give you admin access to the repo and gem

**Comment by cmtonkinson** [comment]
@railsjedi we'd love to adopt the project. We're trying to do the same for @lucasmazza's https://github.com/lucasmazza/ruby-stylus as well since that's no longer actively being maintained.

**Comment by BattleBrisket** [comment]
Just here to confirm that @cmtonkinson and I do in fact work together. We would operate them under the [forgecrafted](https://github.com/forgecrafted) namespace.

**Comment by cmtonkinson** [comment]
Just updated to `0.49.3`; just waiting on rubygems.org access to promulgate.
